language: scala

scala:
  - 2.11.12
  - 2.12.4

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: pL0duvuSN+dYJOXjiYC9muCk/lTACoyqVJQkgR9QyZr4O4AA+X7dWS+klFKCDMMmdHCZ7FXQKJbsPG/2KZpi9nfBI/SIQU5Z2dVY/aRWGaJjivB2e7vLwHSJOg//oYdEkMCtc0MHYO7VuaKGmD6BoJBye2xpj8KRsOAEJDdTr+9ttYQIlPZc6PKabbHR5MnDdIS324LSpGUWfO6dfZuxCU7zMr/KSxs1AtW4vgQRVZEnDvn8NaWDF6IQQ27PNNnYKTdtB7zzKP7+PMz44VarN+hxIDQUBObvtJGBJx/pq0P3eZ8Ms8SIwzdG+pMCTwA/UxP5izihYhFabCR9brDG69S50lyGVSiMpSkzJMkZ5AiiyvveRwPD/JHAdjRo6bNbuEFOZxyKnibiGDb+rNCJuJw6Y1haHOTcU6IY0cBrMc4dIRq187tQqpwoAtonbeTtaqGeBZpNk1mRw9B46bdZ2TTnnV1w8JzdEUuVqwyfNTczyQMZje8WvkWKBblNGE53pr/+Sf8beJGUqhhppHbsuLHbf7cpUESlEZ4/DBtOaHvuotmLqjU2JC0fwm0E8xwgSoXhqh5uR91VlcJ1GC10545y8CCDef3RQ+8zZM6xhtqWQkrj9mFej0c/qMiOeRmayHixUNLlwRx/icLhdg7Yj5YgmATyIq2hFccYjModYjc=
  - secure: cePB0hDju4qF2v6V+n4v3SaQEmoIwGtfKL7iRU5FR7rB8bjReEmDjR09hkxLaS9y3qExT6ifxrCSn5w7ggfCMbqjuGFYhBRX0G+jSv0Gf2/XrSymJMBfNA5JR8qTsKc8YA5sYIxQ0zpdZBKwQyDloNnfPG6Auw9d4m+zbLh+h5gklU4u2tE40QAD68N7tnvCiZj1M2aSHOI9PCoT03mgt9MiJODHFN1TLZGyqUC6VczZKXsEuka3C54hbtYIdy+G51JuV/8/DIr1NmljV44UIxcaIDC7RA9h5O2117LkoqxAQ8UYqZes2G6dezrTErBGJ05GReV0rL3x2hgJ2qJ1x4V6Rr8JI5UXci8iTpSV5+xtx/7MYMnWeBt+6LC51zZKBk9j3iZCFSTYIuh02aYTD0BPonpp8Hc4fUJ/OqNsy3yKkz8wOkHUHmR1RpZDVxy3GpT5u0p9JeT9rISMzUf4mduqD8IVbrKuBcBsQrH5Fu3ksvDAWOSYOrGTDbnT++QAN35VtQtLajD/2WfudDxPsyzz7RAPgH7i5Q15kztp4KemhW7QVyNOmZXyCyZ2+8Zzd+IO9zn6rU5X2Ld3FolJT2dI/qFTDwKYzF6i+2TMq5rpYHzGN0oLaNgEOLwSJU4/9MAx950tq6YIxWtGiFcgguTgozBE5l6z19SIMh/uDb4=
  - secure: nXGynmponkwTunh5Xg+Uo75twSpplp31zkXAP3vAhz95mAs7H50hq3GlgE0pNMIu91m1DhAc34vjPGxnpuniYOVoKMWdVI8Z2wk3bzkCYmRMcXrKx90U0TqzFBc1cnnD9LdQw9zt4BzuasJWDD2iRX8VfSFCSUhe6nh0VCyDP+GFAKhr8xTMzM0F1QplFWsqVpYgo5e/H348lDvmiaa80ybP08PzUqhJ0RAE9+ID90jFIJtbdy8nJsXon+q5kQ5Jm8Ung2rQhH4cE7St5JcdBWPSDlvVXlEEHoD1Bwd3AQsCuKQygXOJSyHwXr2p2Pv11vgUv41i2/aAbXgnnBW8+DjUmIr8z4cHvANa9lAHBM8wx0yn/uFkuiFHc9Ash8x6360kMvar2u/Uf/c2QE51KFO//a/zClOaVAGSDNXKg6eKKGfy0E/pcy6Dyi3u6iUqF/Fgd0ZtMpsjq2WMFFdduvWJ4ciKgk+TCNZwEPFRWB7TxhTbeeBTFuCTapraTfpXcHUi1G4GX4jd7vRvUMBp65VrRItU5tjaB6xJqB0gz5ciVu/MrAwkU9el5e0KH+ZS07yhSfp6qRZNjIb7j6crIXfVpRD6QF2rhaQiWtYWQZ8+ZLbSQZVvVhhnex1QAUDLTQEM3c5DaMxwr3A4nlLT7MmAeYhTKgMsA9ncaMtDBAw=
  - secure: 2ej5beSbY/g8lI6TKaIQNQjI7SxNOmq59t5gOFkIfuTYITy4K7KXtuZ5jJDMCNhtUlonys2FX2DzG8Xi6l0/Lqwur3mOf6NjCOXNIezguarEBx8Ml37+iFQ0Nd9CFCr+nC766PWBzF3odWbcQ7MfJ6ub+G38iuBaMD5H0W8MN9vtWZH9Szl5n+Yd7I/zxvvmACSDhBBwPmi4TyEAbEHKc2MKgPivJp4yleMXAw2n4WtI8i98OkLyUxaKwUdDBvGNRv4PgTbnfO+PIT2wnr4Lz6/zQ+aj9XtvgFM1MTjZL9NG1XzJFd4jTNSUOpR7kPYrLpAjITjQoFYvmQJ2Lrs/qlM6dcQymlAOIXAeGmEoLOeig3aI/i83VTbfOeqn5QtitEd/GqP0+utFBkmMiqoQPIZQS6xMJmjh0TZqS8NmRI9X7BMDVxLYwLyxenqqfpMEfm5glz4S9vvoJD0l3F0dpttEVDatl6nXIx5oL1UM8byedAfSp4ifYTFCgOjBCDQbg6d3EqB4V3uBPmNzCzOPP+QX+4XeAw30mInXXdNne5X24XJm6WCtsgrO8XivhYp6lDn4Ig6Sn7bC1cp5cnpPJCpalwDjmcodPXPsFW/cdZLivcphTw8B9+TnarvtUH+cSqXgx8xK9AFFf5WMxmy6qLOZ6IQFCh2myTHyBd8WH3A=
